name: area-plot-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.6  # or another version you prefer
  - pandas>=2.0.2,<3.0.0
  - plotly>=6.0.0,<7.0.0
  - regex>=2024.11.6,<2025.0.0
  - kaleido>=0.2.0
